### ISSUE TITLE
Failed to create an annotation with Id

### ISSUE THREAD

**Issue by ventil8** [microsoft/ApplicationInsights-Home#442]
With no change to our pipelin we are now getting a failure on our "Add release annotation to Azure Application Insights resource" step.

2019-12-17T20:52:54.7647569Z ##[error]Failed to create an annotation with Id: 61354dbf-c0b1-4c3a-8b1a-18f2648fb085. Error Unknown, Description: Unknown.

I have tried updating the API key as i thought it had gone stale but no luck. The only thing i can think of is that the Live metrics IP address has been changed?

**Comment by Neorth** [comment]
Got the same error on deployments 8 and 3 hours ago.

**Comment by GerritMesker** [comment]
Same problem here. All release annotations in all releases fail at the moment with the above mentioned error.

**Comment by wouterdeman** [comment]
Same problem here. Also getting Error Unknown :(

**Comment by DamianBorndorff** [comment]
Same problem here.. seems like a general outage?

**Comment by ProdSupportGuy** [comment]
We encounter the same problem in all our pipelines

**Comment by tobiasdyrebrant** [comment]
We've got the same issue for our pipelines as well.

**Comment by austinhale** [comment]
Same issue for us

**Comment by michaelvannevel** [comment]
We have the same issue as well.

**Comment by austinhale** [comment]
Messy solution but it works if you need to get a deploy out and can live with not having the annotation in Application Insights: 

Wait until after failure occurs, go into the individual release, click on the failed step (verify you see Pipeline / Tasks / Logs / etc.) on the top, then click on "Edit Release" --> Tasks --> Right click on "Release Annotation" and select "Disable selected task(s)", then click "Save".

Now you have to manually re deploy that release, but it'll re-run and skip the annotations step. Obviously this isn't ideal but it's a workaround.

**Comment by dgritsko** [comment]
There is some discussion of what looks like a similar issue [here](https://marketplace.visualstudio.com/items?itemName=ms-appinsights.appinsightsreleaseannotations&ssr=false#qna). From the discussion on the Q&A page, a Microsoft account said:

>The most recent change that is live in WEU is the removal of support for the older TLS1.0 and TLS1.1 versions of the SSL protocol. This is likely what you are seeing.

>To work around the issue you should [...] enable TLS1.2 by default

**Comment by ventil8** [comment]
If this is against the app service then all mine are already 1.2 but still seeing the issue or can set this against AI?

**Comment by BenLuts** [comment]
> There is some discussion of what looks like a similar issue [here](https://marketplace.visualstudio.com/items?itemName=ms-appinsights.appinsightsreleaseannotations&ssr=false#qna). From the discussion on the Q&A page, a Microsoft account said:
> 
> > The most recent change that is live in WEU is the removal of support for the older TLS1.0 and TLS1.1 versions of the SSL protocol. This is likely what you are seeing.
> 
> > To work around the issue you should [...] enable TLS1.2 by default

Adding the registry keys on our build agents seem to have solved the problem for us!

**Comment by rwatjen** [comment]
That is a machine-wide configuration change, which might break other things.

Is there any chance that we could get a single line added to the beginning of `DeploymentMarker.ps1` in the release task:
```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```
This forces the current PowerShell session to use TLS 1.2.

That is how a lot of the other pipeline tasks from Microsoft are implemented (https://github.com/microsoft/azure-pipelines-tasks/search?q=SecurityProtocolType&unscoped_q=SecurityProtocolType)

**Comment by DamianBorndorff** [comment]
**This one worked for us:**

Step1: Download the CreateReleaseAnnotation.ps1 [here](https://github.com/Microsoft/ApplicationInsights-Home/blob/master/API/CreateReleaseAnnotation.ps1)

Step2: Add Task to YML-File 

```
- task: AzurePowerShell@2
  displayName: 'Create Release annotation'
  inputs:
     azureSubscription: "<enter-your-Subscription>"
     ScriptPath: "<path-to-annotation.ps1>"
     ScriptArguments: '-applicationId  -apiKey  -releaseName $(Build.BuildNumber) -releaseProperties @{"ReleaseDescription"="Release with annotation";"TriggerBy"="Azure DevOps"}'
     azurePowerShellVersion: LatestVersion
  condition: succeeded()
  continueOnError: true
```
